### ISSUE TITLE
AutopilotConfigurationFile.json issue

### ISSUE THREAD

**Issue by eogmau** [rzander/mOSD#4]
Hi Roger,
Accidentally i have left the AutopilotConfigurationFile.json from your repo on my Windows 10 USB and it was added to some of our machines Windows 10, not sure how many. I have noticed it only when they were getting a strange Z-%Serial% name after provisioning to Intune. 

Hopefully that is not a real AutopilotConfigurationFile.json and my machines are not assigned to a different organization for Autopilot?

Can you get back to me please asap?

Thanks, for the great tool 👍

**Comment by rzander** [comment]
No worry, it's an offline autopilot profile... you have to logon (on my tenant) to to fully register the device... The Device-Name is also coming from the JSON-File and not from my Intune-Tenant.

**Comment by eogmau** [comment]
Roger, thanks for confirming this.Happy holidays.On 20 Dec 2019 20:06, Roger Zander <notifications@github.com> wrote:No worry, it's an offline autopilot profile... you have to logon (on my tenant) to to fully register the device... The Device-Name is also coming from the JSON-File and not from my Intune-Tenant.
