### ISSUE TITLE
Unattend part 2 - "modern" OS Deployment (mOSD)

### ISSUE THREAD

**Issue by Mempain** [rzander/mOSD#5]
Hello,
In first, Sorry for my english  :)
Thanks for this arcticle, it's very good job ! :)
I have an error in part 2 of unattend.xml.
With windows 10 2004, I have just need a assigned profile intune and answers for language, region, keyboard is skipped automaticaly.
I configured my unattend.xml with just
<settings pass="auditUser">
            <Reseal>
                <Mode>OOBE</Mode>
            </Reseal>
        </component>
    </settings>
That's ok, but when i use sysprep.exe /oobe /restart /unattend:..unattend.xml, i have one error "windows could not complete the installation restart the installation" .
Without click on the "Ok" button the computer restart and oobe are coming (show "ask your email adress") but it's not very beautifull...
Do you have this error too ? if not do you have a solution for me ?

Thank's in advance for your help :)
Michel

**Comment by rzander** [comment]
can you share your unattend.xml ?
`sysprep.exe /oobe /restart /unattend:..unattend.xml`  ;  you may hove to specify the full path of your unattend.xml.

**Comment by Mempain** [comment]
Hello, 
This is the unattend.xml :) in first when i mount the wim file of windows 10,  I copy the unattend file to windows\system32\sysprep.
Michel

[Unattend.zip](https://github.com/rzander/mOSD/files/4890650/Unattend.zip)

**Comment by rzander** [comment]
Works fine here:
![image](https://user-images.githubusercontent.com/11909453/86928038-54007e00-c134-11ea-89f6-c201063f2cc7.png)

then it will boot into OOBE without Issues:
![image](https://user-images.githubusercontent.com/11909453/86928120-6f6b8900-c134-11ea-9b30-e0bd09bd8fd3.png)

Command is: `sysprep.exe /oobe /reboot /unattend:unattend.xml`

What is the current state of the machine when you run sysprep? Has the machine completed all OS installation steps or are you trying to run sysprep during the setup?

**Comment by Mempain** [comment]
Hello,
Thank's for your fast reply :)
Yes, if i launch the unattend manually that's ok too.
It's after the first unattend.xml with run BootOobe.ps1.
I'm in audit mode.
Michel
[BootOobe.zip](https://github.com/rzander/mOSD/files/4894731/BootOobe.zip)

**Comment by rzander** [comment]
I think your unattend.xml is useless as there is no section for oobeSystem ?! Have you tried the original unattend.xml from mOSD?
Are you sure that sysprep is running from BootOOBE.ps1 ? As I had some Issues that another sysprep was already running...

**Comment by Mempain** [comment]
Re,
Yes i has tested the original unattend.xml from mOSD, i havec the same error.
I wanted to do autoenrollment from winpe, but it's not possible to get the hardware hash... 
So, I used your solution who is very well ! ;) 
I continue my checks...

**Comment by Mempain** [comment]
[WindowsAutomaticenrollment error oobe.zip](https://github.com/rzander/mOSD/files/4895323/WindowsAutomaticenrollment.error.oobe.zip)
In attach, the video with error...see to 3.37 Min

**Comment by Mempain** [comment]
Hello, I find a solution...
I changed the command line &C:\Windows\System32\Sysprep\sysprep.exe /oobe /quiet /reboot /unattend:C:\Windows\system32\sysprep\unattend.xml  **By** Start-Process -FilePath "C:\Windows\System32\Sysprep\sysprep.exe" -ArgumentList "/oobe /quiet /reboot /unattend:C:\Windows\system32\sysprep\unattend.xml" -Wait  and all it's ok, i tested 3 times with no problem.
Thank's for your help
[Windows Automatic Enrollment Ok.zip](https://github.com/rzander/mOSD/files/4901775/Windows.Automatic.Enrollment.Ok.zip)

Best regards, 
Michel

**Comment by rzander** [comment]
Thanks, I've update the BootOOBE.ps1... makes sense to wait. 
https://github.com/rzander/mOSD/commit/1a44fe66310f32d1088e3ca577ef7518a1f0a1fa
