### ISSUE TITLE
Keyboard Language. 

### ISSUE THREAD

**Issue by dbmello75** [rzander/mOSD#8]
Hi, congratulation for share this project with us. 
I've been trying to use the autounattend_US, but I don't know why, they still come with French and German keyboard. 
This is what I edited. 
`            <InputLocale>0409:00020409</InputLocale>`
`            <UILanguage>en-US</UILanguage>`
`            <UserLocale>en-US</UserLocale>`
`            <SystemLocale>en-US</SystemLocale>`

**Comment by dbmello75** [comment]
`            <InputLocale>0409:00020409</InputLocale>
            <UILanguage>en-US</UILanguage>
            <UserLocale>en-US</UserLocale>
            <SystemLocale>en-US</SystemLocale>
`

**Comment by rzander** [comment]
Typo in `<InputLocale>0409:00020409</InputLocale>`, it should be `<InputLocale>0409:00000409</InputLocale>`  ?!
https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-international-core-inputlocale

**Comment by dbmello75** [comment]
Thank you for your fast reply. 

`<InputLocale>0409:00020409</InputLocale>`  is for English International, I need this to write Portuguese words in an en-US Windows. 
I found this:
$OEM$\$$\System32\sysprep\unattend.xml. 
It has some entries that change the keyboard.

**Comment by rzander** [comment]
My Version of `$OEM$$$\System32\sysprep\unattend.xml` does no longer have keyboard settings... I think you can remove these entries... I will update the example in this Repository.

**Comment by dbmello75** [comment]
Thank you. I've changed the entries and it works.
